version: '3.9'

services:
  backend:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - 1000:1000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy # รอให้ PostgreSQL พร้อมก่อน
    environment:
      DATABASE_URL: postgres://root:123456@db:5432/ecom
    command: ["sh", "-c", "npm install && npm run start"]

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: ['postgres', '-c', 'max_connections=200']
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  pgdata: