version: '3.9'
services:
  backend:
    build: .
    ports:
      - 1000:1000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest # เปลี่ยนรูปภาพ Docker ไปเป็น PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: ecom # กำหนดชื่อฐานข้อมูล
      POSTGRES_USER: root # กำหนดผู้ใช้
      POSTGRES_PASSWORD: 123456 # กำหนดรหัสผ่าน
    volumes:
      - .pgdata:/var/lib/postgresql/data # เปลี่ยนชื่อโฟลเดอร์ที่จะใช้เก็บข้อมูล PostgreSQL
    ports:
      - 5432:5432
    command: ['postgres', '-c', 'max_connections=200'] # เพิ่มคำสั่งนี้
