name: Deploy ECOM BackEnd App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ecom
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 123456
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U root" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker-compose down
          docker-compose up -d --build